---
- name: New users are created
  hosts: all
  become: true
  vars:
    web_servers:
      - member
      - admin
      - developer

  tasks: 
    - name: Create database users
      user: 
        name: "{{ item }}"
        state: present
      loop: "{{ db_users }}"
      when: "'databases' in group_names"

    - name: Create webserver users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ web_servers }}"
      when: "'webservers' in group_names"
